name: CI devops 2023
on:
  # Pour commencer, vous voulez lancer ce travail sur les branches main et develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:

  test-backend: 
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      # Récupérez votre code GitHub en utilisant actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Configurez le JDK 17 avec actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt' # Spécifiez la distribution (dans cet exemple, j'utilise AdoptOpenJDK)        

      # Enfin, construisez et testez votre application avec la commande appropriée
      - name: Build and test with Maven
        run: mvn -f ./backend_API2/pom.xml clean install # Spécifiez explicitement le chemin vers le fichier POM

# define job to build and publish docker image
  build-and-push-docker-image:
   needs: test-backend
 # run only when code is compiling and tests are passing
   runs-on: ubuntu-22.04

 # steps to perform in job
   steps:
     - name: Checkout code
       uses: actions/checkout@v2.5.0
  
     - name: Build image and push backend
       uses: docker/build-push-action@v3
       with:
         # relative path to the place where source code with Dockerfile is located
         context: ./simple-api
         # Note: tags has to be all lower-case
         tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops/simple-api
  
     - name: Build image and push database
       uses: docker/build-push-action@v3
       with:
         # relative path to the place where source code with Dockerfile is located
         context: ./simple-api
         # Note: tags has to be all lower-case
         tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops/simple-api  
     - name: Build image and push httpd
       uses: docker/build-push-action@v3
       with:
         # relative path to the place where source code with Dockerfile is located
         context: ./simple-api
         # Note: tags has to be all lower-case
         tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops/simple-api
  
