name: CI devops 2023
on:
  # Pour commencer, vous voulez lancer ce travail sur les branches main et develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Récupérez votre code GitHub en utilisant actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Configurez le JDK 17 avec actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt' # Spécifiez la distribution (dans cet exemple, j'utilise AdoptOpenJDK)
     
     # Définissez le répertoire de travail de Maven
      - name: Set up Maven
        run: mvn -N io.takari:maven:0.7.7:wrapper
      - name: Set working directory
        run: cd ../../backend_API2/
        
      # Enfin, construisez et testez votre application avec la commande appropriée
      - name: Build and test with Maven
        run: mvn clean install # Vous devrez utiliser la commande réelle pour construire votre application avec Maven
